# Site settings
title: Data Science Initiative
email: datascience@uci.edu
description: > # this means to ignore newlines until "baseurl:"
    This site provides information about DSI workshops and recommended resources. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ucidatascienceinitiative.github.io" # the base hostname & protocol for your site
facebook_username: uci.datascience
facebook_word: Facebook
github_username:  UCI DSI
github_word: Github
venue: University of California, Irvine

dsi_site: "http://datascience.uci.edu"
dsi_ws: "http://ucidatascienceinitiative.github.io"
dsi_facebook: "https://www.facebook.com/uci.datascience/"
dsi_github: "https://github.com/UCIDataScienceInitiative"


# Jekyll Build settings
markdown        : kramdown
kramdown        :
    entity_output: as_input
